# Generated by Django 2.2.1 on 2019-05-24 08:11

from django.db import migrations
import datetime


def convert_datetime(apps, schema_editor):
    Menu = apps.get_model('menu', 'Menu')
    for menu in Menu.objects.all():
        menu.created_date = datetime.date(year=menu.created_date.year,
                                          month=menu.created_date.month,
                                          day=menu.created_date.day)
        menu.save()

        if menu.expiration_date:
            menu.expiration_date = datetime.date(year=menu.expiration_date.year,
                                                 month=menu.expiration_date.month,
                                                 day=menu.expiration_date.day)
            menu.save()


def convert_item_datetime(apps, schema_editor):
    Item = apps.get_model('menu', 'Item')
    for item in Item.objects.all():
        item.created_date = datetime.date(year=item.created_date.year,
                                          month=item.created_date.month,
                                          day=item.created_date.day)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_datetime),
        migrations.RunPython(convert_item_datetime)
    ]
